<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.heliosares</groupId>
    <artifactId>AuxProtect</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>AuxProtect</name>

    <modules>
        <module>AuxProtect_Core</module>

        <module>AuxProtect_Spigot_1.20</module>
        <module>AuxProtect_Spigot_1.21</module>
        <module>AuxProtect_Spigot</module>

        <module>AuxProtect_Velocity</module>

        <module>AuxProtect_Package</module>
    </modules>

    <profiles>
        <profile>
            <id>include-auxprotect-private</id>
            <modules>
                <module>AuxProtect_PrivateModule</module>
            </modules>
        </profile>
    </profiles>

    <properties>
        <project.build.sourceEncoding>UTF8</project.build.sourceEncoding>
        <revision>1.4-pre1</revision>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <!--<version>1.7.0</version>-->
                <configuration>
                </configuration>
                <executions>
                    <!-- enable flattening -->
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <!-- ensure proper cleanup -->
                    <execution>
                        <id>flatten.clean</id>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <extensions>
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-ssh-external</artifactId>
                <version>3.5.3</version>
            </extension>
        </extensions>
    </build>

    <repositories>
        <repository>
            <id>kshl-repo</id>
            <url>https://maven.atownyserver.com/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>dev.kshl</groupId>
            <artifactId>KshLib</artifactId>
            <version>2.0</version>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>toaster5</id>
            <url>scpexe://toaster5/var/www/maven</url>
        </repository>
        <snapshotRepository>
            <id>toaster5</id>
            <url>scpexe://toaster5/var/www/maven</url>
        </snapshotRepository>
    </distributionManagement>
</project>
