name: AuxProtect
version: '${project.version}'
main: dev.heliosares.auxprotect.spigot.AuxProtectSpigot
description: A plugin designed to supplement CoreProtect in a few ways.
api-version: 1.13
folia-supported: true
softdepend: [
  AuctionHouse,
  ChestShop,
  CoreProtect,
  DynamicShop,
  EconomyShopGUI,
  EconomyShopGUI-Premium,
  Essentials,
  PlayerAuctions,
  ProtocolLib,
  Jobs,
  ShopGUIPlus,
  Towny,
  Vault
]
loadbefore: [
  AdvancedPortals,
  AnnouncerPlus,
  ajParkour
]

commands:
  auxprotect:
    usage: /auxprotect
    description: Base command
    aliases: [ ap,aux ]
  claiminv:
    usage: /claiminv
    description: Claim a recovered inventory
  cslogs:
    usage: /cslogs
    description: View your recent ChestShop logs